omic_meta_data:
   /home/groups/CEDAR/roskamsh/projects/Bulk-RNA-seq-pipeline-SE/data/RNAseq_metadata_JK.txt
base_dir:
  /home/groups/CEDAR/roskamsh/projects/Bulk-RNA-seq-pipeline-SE
gtf_file:
  /home/exacloud/lustre1/CEDAR/anurpa/genomes/gencode.v27.annotation.gtf
bed_file:
  /home/exacloud/lustre1/CEDAR/roskamsh/projects/Omics-QC-pipeline/data/gencode_v27.bed
exon_gtf:
  /home/exacloud/lustre1/CEDAR/anurpa/genomes/gencode.housekeeping_genes.exon.gtf
adapter-SE:
  /home/exacloud/lustre1/CEDAR/roskamsh/projects/Omics-QC-pipeline/data/TruSeq2-SE.fa
conf:
  /home/groups/CEDAR/tools/FastQ_Screen_Genomes/fastq_screen.conf
#path to tools
star_tool:
  /home/exacloud/lustre1/CEDAR/tools/STAR/tags/2.5.3a/bin/Linux_x86_64/STAR
picard_tool:
  /home/exacloud/lustre1/CEDAR/tools/picard-tools-1.119/MarkDuplicates.jar
bamstats_tool:
  /home/groups/CEDAR/roskamsh/tools/bamstats_bin/bamstats
genome:
  /home/exacloud/lustre1/CEDAR/anurpa/genomes/GRCh38.primary_assembly.genome.fa
refflat2:
  /home/exacloud/lustre1/CEDAR/Genomes/gencode27_refflat2.txt
star_index:
  /home/exacloud/lustre1/CEDAR/anurpa/genomes/
project_id:
  JK_Bulk
assembly:
  hg38.90
baseline:
  HD
linear_model:
  Type
seq_layout:
  SE
sample_id:
  StudyID
dds_design:
  SampleID
rseqc_env:
  source activate rseqc-omic-wf
meta_columns_to_plot:
  Type: Type
  Notes: Notes
  RNA_extraction_date: RNA_extraction_date
diffexp:
  # contrasts for the deseq2 results method
  contrasts:
    #HD-vs-MM:
    #  - HD
    #  - MM
    HD-vs-LCx:
      - HD
      - LCx
pca:
  labels:
    # columns of sample sheet to use for PCA
    - Type
# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: /home/groups/CEDAR/roskamsh/projects/Bulk-RNA-seq-pipeline-SE/data/RNAseq_metadata_JK.txt
