##############################################################################
# Genome and project-specific files that will change from project-to-project
##############################################################################

# GTF file for the genome build you would like to use
gtf_file:
  /home/travis/build/ohsu-cedar-comp-hub/Bulk-RNA-seq-pipeline-SE/.test/resources/chr21.gtf
# Bed file for rseqc function read_distribution
bed_file:
  /home/travis/build/ohsu-cedar-comp-hub/Bulk-RNA-seq-pipeline-SE/.test/resources/chr21.bed
# Pre-built star indexes for hg38
star_index:
  resources/

filter_anno:
  /home/travis/build/ohsu-cedar-comp-hub/Bulk-RNA-seq-pipeline-SE/.test/resources/hg38.Ens_90.biomaRt.geneAnno.Rdata

biotypes:
  protein_coding

####################################################################
# Tool-specific files that will not change from project-to-project
####################################################################

# Fasta file including the illumina adapters to be trimmed out via Trimmomatic
adapter:
  resources/TruSeq2-SE.fa
# Pre-built genome indexes for various organisms which we will screen against to look for contamination
conf:
  FastQ_Screen_Genomes/fastq_screen.conf
# Paths to various tools which are used in this pipeline
star_tool:
  STAR
# Path to omic resources repository
code_dir:
  /home/travis/build/ohsu-cedar-comp-hub/Bulk-RNA-seq-pipeline-SE/.test/resources/omic_resources/
##########################################
# Important project-specific paths/files
##########################################

# Metadata needed for differential expression analysis
omic_meta_data:
  /home/travis/build/ohsu-cedar-comp-hub/Bulk-RNA-seq-pipeline-SE/.test/data/metadata.txt
# Path to your base directory (path to this directory)
base_dir:
  /home/travis/build/ohsu-cedar-comp-hub/Bulk-RNA-seq-pipeline-SE/.test

#############################################################################################
# Project-specific specifications you will need to make prior to submission of the pipeline
#############################################################################################

# Unique project identifier which will be concatenated onto your counts table file name.
project_id:
  TravisCI
# Genome assembly used for GO analysis, format must be as below, with the genome assembly first, and the version of ensembl second, separated by a period.
assembly:
  hg38.90
# The "baseline" used for your differential expression analysis. Ex: Healthy, WT, etc.
# remove mito genes (1/0)
mito:
  1
#option to print GOterm tree (0/1)
printTree:
  1
#fold change cutoff (not log2 transformed) for GO analysis
FC:
  2
#FDR adjusted p-value cutoff for GO analysis
adjp:
  0.01
baseline:
  WT
# The column name of the characteristic you would like to do DE on. Example: Diagnosis, genotype, etc. This must be a column in your omic_meta_data.
linear_model:
  Condition
# The column name in which your sampleIDs are defined in omic_meta_data. These should match the sampleIDs in your fastq files.
sample_id:
  SampleID
# The column names in your omic_meta_data file which you would like to annotate your heatmaps by. This is used as a QC to look for batch effects. Enter columns which could potentially introduce a batch effect in your data.
meta_columns_to_plot:
  Condition: Condition
  KnockDown: KnockDown
  Treatment: Treatment
# Contrasts which you would like to run differential expression on.
# For example if you want to look at wild type (wt) vs. mutant (mut), you would specify mut-vs-wt
# It is important that when listing your types here, you write your baseline SECOND
diffexp:
  # contrasts for the deseq2 results method
  contrasts:
    siKD-vs-WT:
      - siKD
      - WT
  LRT:
    - siKD
    - WT

# The column name in your omic_meta_data file to colour your PCA plot by
pca:
  labels:
  # columns of sample sheet to use for PCA
    - Condition

colors:
  rcolorbrewer:
    - NA
  discrete:
    - NA